<?php

/**
 * @file
 * Contains olympe.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function olympe_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the olympe module.
    case 'help.page.olympe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Centre du controle du blog') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function olympe_theme()
{
  $theme = [];

  return $theme;
}


/**
 *  Implements hook_preprocess_HOOK().
 */
function olympe_preprocess_html(&$variables) {
  $user_authenticated = \Drupal::currentUser()->isAuthenticated();
  if($user_authenticated){
      $variables['attributes']['class'][] = 'user-authenticated';
  }
}