<?php

/**
 * @file
 * Contains blog_articles.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function blog_articles_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the blog_articles module.
    case 'help.page.blog_articles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion des articles du blog') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function blog_articles_theme()
{
  $theme = [];

  return $theme;
}

/**
 * Implements hook_entity_view_alter().
 */
function blog_articles_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {

  /**
   * Implementation de la condition de rendu pour les terms de taxonomy.
   */
  if(isset($build['#taxonomy_term']) && $entity->getVocabularyId() == 'tags'){
    $query = \Drupal::entityQuery('node');
    $query->condition('type', 'articles');
    $query->condition('status', 1);
    $query->condition('field_tags.target_id', $entity->id(), '=');
    $query->sort('created', 'DESC');
    $query->range(0,10);
    $result = $query->execute();
    $build['content'] = '';
    if(isset($result[1])){
      $build['content'] = entity_view_multiple(entity_load_multiple('node', $result), 'teaser');
    }
  }
}
