<?php

/**
 * @file
 * Contains test1.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function test1_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the test1 module.
    case 'help.page.test1':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('lol') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function test1_theme()
{
  $theme = [];

  return $theme;
}
